exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('comments').del()
    .then(function () {
      // Inserts seed entries
      return knex('comments').insert([
        {comments: "Construction site - your car will get dirty!", parking_id: 1},
        {comments: "Don't recommend parking here!", parking_id: 1},
        {comments: "I'll never park here again", parking_id: 1},
        {comments: "School zone - don't park during the day", parking_id: 2},
        {comments: "Good for parking on weekends", parking_id: 2},
        {comments: "I parked here overnight and it was fine", parking_id: 2},
        {comments: "Very busy", parking_id: 3},
        {comments: "You can park if your car is small", parking_id: 3},
        {comments: "Very difficult to find a spot", parking_id: 3},
        {comments: "Construction site - your car will get dirty!", parking_id: 4},
        {comments: "Don't recommend parking here!", parking_id: 4},
        {comments: "I'll never park here again", parking_id: 4},
        {comments: "School zone - don't park during the day", parking_id: 5},
        {comments: "Good for parking on weekends", parking_id: 5},
        {comments: "I parked here overnight and it was fine", parking_id: 5},
        {comments: "Very busy", parking_id: 6},
        {comments: "You can park if your car is small", parking_id: 6},
        {comments: "Very difficult to find a spot", parking_id: 6},
        {comments: "I didn't see the sign! My car got towed!", parking_id: 7},
        {comments: "Watch out for the hidden no parking sign!", parking_id: 7},
        {comments: "Can't park here!", parking_id: 7},
        {comments: "No parking for more than 1hour! I got a ticket", parking_id: 8},
        {comments: "Careful, you'll seriously get a ticket if you exceed the 1h limit", parking_id: 8},
        {comments: "What? The ticket is horribly expensive!", parking_id: 8},
        {comments: "Very busy", parking_id: 9},
        {comments: "You can park if your car is small", parking_id: 9},
        {comments: "Very difficult to find a spot", parking_id: 9},
        {comments: "Very busy", parking_id: 10},
        {comments: "You can park if your car is small", parking_id: 10},
        {comments: "Very difficult to find a spot", parking_id: 10},
        {comments: "I didn't see the sign! My car got towed!", parking_id: 11},
        {comments: "Watch out for the hidden no parking sign!", parking_id: 11},
        {comments: "Can't park here!", parking_id: 11},
        {comments: "No parking for more than 1hour! I got a ticket", parking_id: 12},
        {comments: "Careful, you'll seriously get a ticket if you exceed the 1h limit", parking_id: 12},
        {comments: "What? The ticket is horribly expensive!", parking_id: 12},
        {comments: "Construction site - your car will get dirty!", parking_id: 13},
        {comments: "Don't recommend parking here!", parking_id: 13},
        {comments: "I'll never park here again", parking_id: 13},
        {comments: "School zone - don't park during the day", parking_id: 14},
        {comments: "Good for parking on weekends", parking_id: 14},
        {comments: "I parked here overnight and it was fine", parking_id: 14},
        {comments: "Construction site - your car will get dirty!", parking_id: 15},
        {comments: "Don't recommend parking here!", parking_id: 15},
        {comments: "I'll never park here again", parking_id: 15},
        {comments: "School zone - don't park during the day", parking_id: 16},
        {comments: "Good for parking on weekends", parking_id: 16},
        {comments: "I parked here overnight and it was fine", parking_id: 16},
        {comments: "Construction site - your car will get dirty!", parking_id: 17},
        {comments: "Don't recommend parking here!", parking_id: 17},
        {comments: "I'll never park here again", parking_id: 17},
        {comments: "School zone - don't park during the day", parking_id: 18},
        {comments: "Good for parking on weekends", parking_id: 18},
        {comments: "I parked here overnight and it was fine", parking_id: 18},
        {comments: "Construction site - your car will get dirty!", parking_id: 19},
        {comments: "Don't recommend parking here!", parking_id: 19},
        {comments: "I'll never park here again", parking_id: 19},
        {comments: "School zone - don't park during the day", parking_id: 20},
        {comments: "Good for parking on weekends", parking_id: 20},
        {comments: "I parked here overnight and it was fine", parking_id: 20},
        {comments: "Construction site - your car will get dirty!", parking_id: 21},
        {comments: "Don't recommend parking here!", parking_id: 21},
        {comments: "I'll never park here again", parking_id: 21},
        {comments: "School zone - don't park during the day", parking_id: 22},
        {comments: "Good for parking on weekends", parking_id: 22},
        {comments: "I parked here overnight and it was fine", parking_id: 22},
        {comments: "Very busy", parking_id: 23},
        {comments: "You can park if your car is small", parking_id: 23},
        {comments: "Very difficult to find a spot", parking_id: 23},
        {comments: "Construction site - your car will get dirty!", parking_id: 24},
        {comments: "Don't recommend parking here!", parking_id: 24},
        {comments: "I'll never park here again", parking_id: 24},
        {comments: "School zone - don't park during the day", parking_id: 25},
        {comments: "Good for parking on weekends", parking_id: 25},
        {comments: "I parked here overnight and it was fine", parking_id: 25},
        {comments: "Very busy", parking_id: 26},
        {comments: "You can park if your car is small", parking_id: 26},
        {comments: "Very difficult to find a spot", parking_id: 26},
        {comments: "I didn't see the sign! My car got towed!", parking_id: 27},
        {comments: "Watch out for the hidden no parking sign!", parking_id: 27},
        {comments: "Can't park here!", parking_id: 27},
        {comments: "No parking for more than 1hour! I got a ticket", parking_id: 28},
        {comments: "Careful, you'll seriously get a ticket if you exceed the 1h limit", parking_id: 28},
        {comments: "What? The ticket is horribly expensive!", parking_id: 28},
        {comments: "Very busy", parking_id: 29},
        {comments: "You can park if your car is small", parking_id: 29},
        {comments: "Very difficult to find a spot", parking_id: 29},
        {comments: "Very busy", parking_id: 30},
        {comments: "You can park if your car is small", parking_id: 30},
        {comments: "Very difficult to find a spot", parking_id: 30},
        {comments: "I didn't see the sign! My car got towed!", parking_id: 31},
        {comments: "Watch out for the hidden no parking sign!", parking_id: 31},
        {comments: "Can't park here!", parking_id: 31},
        {comments: "No parking for more than 1hour! I got a ticket", parking_id: 32},
        {comments: "Careful, you'll seriously get a ticket if you exceed the 1h limit", parking_id: 32},
        {comments: "What? The ticket is horribly expensive!", parking_id: 32},
        {comments: "Construction site - your car will get dirty!", parking_id: 33},
        {comments: "Don't recommend parking here!", parking_id: 33},
        {comments: "I'll never park here again", parking_id: 33},
        {comments: "School zone - don't park during the day", parking_id: 34},
        {comments: "Good for parking on weekends", parking_id: 34},
        {comments: "I parked here overnight and it was fine", parking_id: 34},
        {comments: "Construction site - your car will get dirty!", parking_id: 35},
        {comments: "Don't recommend parking here!", parking_id: 35},
        {comments: "I'll never park here again", parking_id: 35},
        {comments: "School zone - don't park during the day", parking_id: 36},
        {comments: "Good for parking on weekends", parking_id: 36},
        {comments: "I parked here overnight and it was fine", parking_id: 36},
        {comments: "Construction site - your car will get dirty!", parking_id: 37},
        {comments: "Don't recommend parking here!", parking_id: 37},
        {comments: "I'll never park here again", parking_id: 37},
        {comments: "School zone - don't park during the day", parking_id: 38},
        {comments: "Good for parking on weekends", parking_id: 38},
        {comments: "I parked here overnight and it was fine", parking_id: 38},
        {comments: "Construction site - your car will get dirty!", parking_id: 39},
        {comments: "Don't recommend parking here!", parking_id: 39},
        {comments: "I'll never park here again", parking_id: 39},
        {comments: "School zone - don't park during the day", parking_id: 40},
        {comments: "Good for parking on weekends", parking_id: 40},
        {comments: "I parked here overnight and it was fine", parking_id: 40},
                {comments: "You can park if your car is small", parking_id: 30},
        {comments: "Very difficult to find a spot", parking_id: 30},
        {comments: "I didn't see the sign! My car got towed!", parking_id: 31},
        {comments: "Watch out for the hidden no parking sign!", parking_id: 31},
        {comments: "Can't park here!", parking_id: 31},
        {comments: "No parking for more than 1hour! I got a ticket", parking_id: 32},
        {comments: "Careful, you'll seriously get a ticket if you exceed the 1h limit", parking_id: 32},
        {comments: "What? The ticket is horribly expensive!", parking_id: 32},
        {comments: "Construction site - your car will get dirty!", parking_id: 33},
        {comments: "Don't recommend parking here!", parking_id: 33},
        {comments: "I'll never park here again", parking_id: 33},
        {comments: "School zone - don't park during the day", parking_id: 34},
        {comments: "Good for parking on weekends", parking_id: 34},
        {comments: "I parked here overnight and it was fine", parking_id: 34},
        {comments: "Construction site - your car will get dirty!", parking_id: 35},
        {comments: "Don't recommend parking here!", parking_id: 35},
        {comments: "I'll never park here again", parking_id: 35},
        {comments: "School zone - don't park during the day", parking_id: 36},
        {comments: "Good for parking on weekends", parking_id: 36},
        {comments: "I parked here overnight and it was fine", parking_id: 36},
        {comments: "Construction site - your car will get dirty!", parking_id: 37},
        {comments: "Don't recommend parking here!", parking_id: 37},
        {comments: "I'll never park here again", parking_id: 37},
        {comments: "School zone - don't park during the day", parking_id: 38},
        {comments: "Good for parking on weekends", parking_id: 38},
        {comments: "I parked here overnight and it was fine", parking_id: 38},
        {comments: "Construction site - your car will get dirty!", parking_id: 39},
        {comments: "Don't recommend parking here!", parking_id: 39},
        {comments: "I'll never park here again", parking_id: 39},
        {comments: "School zone - don't park during the day", parking_id: 40},
        {comments: "Good for parking on weekends", parking_id: 40},
        {comments: "I parked here overnight and it was fine", parking_id: 40},
        {comments: "I didn't see the sign! My car got towed!", parking_id: 41},
        {comments: "Watch out for the hidden no parking sign!", parking_id: 41},
        {comments: "Can't park here!", parking_id: 41},
        {comments: "No parking for more than 1hour! I got a ticket", parking_id: 42},
        {comments: "Careful, you'll seriously get a ticket if you exceed the 1h limit", parking_id: 42},
        {comments: "What? The ticket is horribly expensive!", parking_id: 42},
        {comments: "Construction site - your car will get dirty!", parking_id: 43},
        {comments: "Don't recommend parking here!", parking_id: 43},
        {comments: "I'll never park here again", parking_id: 43},
        {comments: "School zone - don't park during the day", parking_id: 44},
        {comments: "Good for parking on weekends", parking_id: 44},
        {comments: "I parked here overnight and it was fine", parking_id: 44},
        {comments: "Construction site - your car will get dirty!", parking_id: 45},
        {comments: "Don't recommend parking here!", parking_id: 45},
        {comments: "I'll never park here again", parking_id: 45},
        {comments: "School zone - don't park during the day", parking_id: 46},
        {comments: "Good for parking on weekends", parking_id: 46},
        {comments: "I parked here overnight and it was fine", parking_id: 46},
        {comments: "Construction site - your car will get dirty!", parking_id: 47},
        {comments: "Don't recommend parking here!", parking_id: 47},
        {comments: "I'll never park here again", parking_id: 47},
        {comments: "School zone - don't park during the day", parking_id: 48},
        {comments: "Good for parking on weekends", parking_id: 48},
        {comments: "I parked here overnight and it was fine", parking_id: 48},
        {comments: "Construction site - your car will get dirty!", parking_id: 49},
        {comments: "Don't recommend parking here!", parking_id: 49},
        {comments: "I'll never park here again", parking_id: 49},
        {comments: "School zone - don't park during the day", parking_id: 50},
        {comments: "Good for parking on weekends", parking_id: 50},
        {comments: "I parked here overnight and it was fine", parking_id: 50},  
        {comments: "School zone - don't park during the day", parking_id: 51},
        {comments: "Good for parking on weekends", parking_id: 51},
        {comments: "I parked here overnight and it was fine", parking_id: 51},
        {comments: "Construction site - your car will get dirty!", parking_id: 52},
        {comments: "Don't recommend parking here!", parking_id: 52},
        {comments: "I'll never park here again", parking_id: 52},
        {comments: "School zone - don't park during the day", parking_id: 53},
        {comments: "Good for parking on weekends", parking_id: 53},
        {comments: "I parked here overnight and it was fine", parking_id: 53},
        {comments: "Construction site - your car will get dirty!", parking_id: 54},
        {comments: "Don't recommend parking here!", parking_id: 54},
        {comments: "I'll never park here again", parking_id: 54},
        {comments: "School zone - don't park during the day", parking_id: 55},
        {comments: "Good for parking on weekends", parking_id: 55},
        {comments: "I parked here overnight and it was fine", parking_id: 55}   
      ]);
    });
};